version: "3.8"

services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service" # The image used to run the container
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001 # The port where the JVM will listen for debug connections
    environment:
      - BPL_JVM_THREAD_COUNT=50 # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888 # The URL of the config server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog # The URL of the PostgreSQL database
      - SPRING_PROFILES_ACTIVE=testdata

  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      - BPL_JVM_THREAD_COUNT=50 # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
