version: "3.8"

services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service" # The image used to run the container
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50 # Buildpacks environment variable to configure the number of threads in memory calculation
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog # The URL of the PostgreSQL database
      - SPRING_PROFILES_ACTIVE=testdata


  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
